#ifndef SYMBOLS_H
#define SYMBOLS_H
/* Combine include guard and pragma once for compatibility reasons */
#pragma once

/* ##############   Includes   ############## */
#include <stddef.h>
#include <stdint.h>

/* ##############   Typedefs   ############## */
typedef struct _symbol_s {
    const uintptr_t sym_addr;
    const char *sym_name;
    const char *handler;
} symbol_t;

typedef void (*generic_func_t)(void);

/* ############   Declarations   ############ */
/* Symbols will be autogenerated into a symbols.c file */
extern const symbol_t symbols[];
extern const size_t symbol_num;


#endif /* SYMBOLS_H */
